name: PR Build Check for API Sanity

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Extract PR body
      id: extract_body
      run: |
        echo "PR_BODY<<EOF" >> $GITHUB_ENV
        echo "${{ github.event.pull_request.body }}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV


    - name: Comment on PR if validation failed
      if: env.VALIDATION_FAILED == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const missing = process.env.MISSING_FIELDS;
          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `⚠️ **The following required sections are missing or invalid in the PR description:**\n\n${missing.split('|||').map(x => `- ${x}`).join('\n')}\n\nPlease fill them in before this PR can be tested.`
          });

    - name: Fail job if validation failed
      if: env.VALIDATION_FAILED == 'true'
      run: exit 1

    - name: Run Maven tests
      if: env.VALIDATION_FAILED != 'true'
      run: mvn test 
      #-Denvironment=dev11 -DsuiteXmlFile=suite/${{ env.SUITE_FILE }}.xml -DtestFailureIgnore=false
